name: PHPUnitの実行
on: [ push ]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: '環境の起動とテスト'
        run: | 
          docker-compose up -d
          sleep 30  # 10秒待機
          while ! docker-compose exec -T db mysqladmin ping --host=127.0.0.1 --user=laravel --password=password --silent; do
            echo "mysqlの起動を待っています"
            sleep 30
          done
          cp src/.env.example src/.env
          docker-compose exec -T app ls -l
          docker-compose exec -T app php artisan config:clear
          docker-compose exec -T app composer install
          docker-compose exec -T app php artisan key:generate
          
      - name: 'PHPUnitの実行'
        run: |
          docker-compose exec -T app php artisan migrate:fresh --env=testing
          docker-compose exec -T app vendor/bin/phpunit --debug
